# Generated by Django 4.2.6 on 2023-10-11 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="publish_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
